### ISSUE TITLE
Azure core quota limit reached

### ISSUE THREAD

**Issue by spacecat** [Microsoft/SmartHotel360-Azure-backend#19]
I have a VM running Ubuntu ( I think I set the size to 4 cores ). This VM lives in a resource group along with the rest of the usual resources that get spun up when creating a new VM (NSG, Store Account etc). This is all I have in my free trial subscription.

Now I'm trying to create the k8s cluster but ran into the following problem:

```


Deployment failed. Correlation ID: 02addf4d-80dc-4dcf-8479-db9142bd140f. {
  "error": {
    "code": "QuotaExceeded",
    "message": "Provisioning of resource(s) for container service 'smart-hotel-360-backend-aks' in resource group 'smart-hotel-360-backend-rg' failed.\nMessage: 'Operation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 4, Additional requested: 4. Please read more about quota increase at http://aka.ms/corequotaincrease.'.\nDetails: ''"
  }
}
```

This is not really related to SmartHotel360 but running a free trial account with 1 Ubuntu VM makes it hard to test these Azure services with the 4 core quota limit.

I could lower the cores on the Ubuntu VM but then I would have really poor performance as I'm already struggling with poor RDP ubuntu desktop refresh rates (I've already set the RDP display settings to a minimum to keep the refresh rates at a decent level).

I would run an Ubuntu laptop / VM locally but currently I don't have the possibility to do that - that's why I created the Ubuntu VM with ubuntu-desktop in Azure.

I understand if it is not possible to increase the quota for free trial Azure accounts, are there any other alternatives if you want to deploy the cluster and resources in Azure (for non-paying / non-enterprise customers)?

**Comment by eiximenis** [comment]
Hi

One option is to run the k8s cluster locally. This can be easily achieved using [minikube](https://github.com/kubernetes/minikube) or the latest edge version of Docker CE for Windows or Mac that has local k8s management.

We have not tested the services using local k8s but as long as the VM running the cluster has enought memory it should work.

**Comment by bradygmsft** [comment]
@spacecat this is a great question. One thing I'm currently working on is an entire setup of the topology, all the demos - everything - to allow it to run in a specified environment for a month so we can get a crisp estimate of the overall cost options. A topology the scope of SmartHotel360 has a **lot** of resources and compute power, but to get the environment set up in a development scenario isn't unreasonable. 

I used the [Azure pricing calculator](https://azure.microsoft.com/en-us/pricing/calculator/) and came up with the table below. Note - YMMV here, but this is based on a few topology assumptions, like rather than using an Ubuntu desktop using one of our services, like ACS or AKS. I included a larger Ubuntu desktop in here if that's your preference, too. The table also presumes a **3-day lifetime** on the resources. If you leave them alive for a month, the prices would go up. 

|Resource Type|# Units|Cost|
|---|---|---|
|Container Registry|1|$.93|
|AKS Cluster|4 Cores, 16 GB RAM, 32GB Storage|$12.18|

The other resources - like the serverless Function, the Public Web Site, and the Cognitive Services components and Bing Maps API, have free tiers. 

Hope this helps! I'll close this issue for now, but if you have other ideas on how we can better document the potential costs, please let us know.
